# @covers AC-028, AC-030, AC-070
"""Shared test helpers: workspaces, a fake Anthropic client, CLI invocation."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest

REPO = Path(__file__).resolve().parent.parent
# @assumption AS-021 - generated by scripts/make_sample_tree.py; reserved names are made at test time
SAMPLE_TREE = REPO / "tests" / "fixtures" / "sample_tree"

TAXONOMY = """\
categories:
  - slug: contracts
    name: contracts agreement nda
    description: legal documents
    subcategories: [nda, outsourcing]
  - slug: specs
    name: specs specification architecture
    description: specifications and design
  - slug: meetings
    name: meeting minutes sync
    description: meeting notes
"""


@pytest.fixture(autouse=True)
def _isolated_env(monkeypatch: pytest.MonkeyPatch) -> None:
    for k in ("DN_LLM_REPLAY", "DN_LLM_RECORD", "DN_LLM_FIXTURES"):
        monkeypatch.delenv(k, raising=False)


@pytest.fixture
def target(tmp_path: Path) -> Path:
    t = tmp_path / "target"
    t.mkdir()
    return t


def write(root: Path, rel: str, data: str | bytes) -> Path:
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(data, bytes):
        p.write_bytes(data)
    else:
        p.write_bytes(data.encode("utf-8"))
    return p


def with_taxonomy(root: Path, text: str = TAXONOMY) -> None:
    (root / "taxonomy.yaml").write_text(text, encoding="utf-8")


def copy_sample(dest: Path) -> Path:
    shutil.copytree(SAMPLE_TREE, dest, dirs_exist_ok=True)
    with_taxonomy(dest)
    return dest


def open_ws(root: Path, **kw: Any):  # type: ignore[no-untyped-def]
    from dn.workspace import Workspace

    return Workspace.open(root, **kw)


def run_dn(
    *args: str, cwd: Path | None = None, env: dict[str, str] | None = None, input: str | None = None
) -> subprocess.CompletedProcess[str]:
    """Run the real CLI in a subprocess (separate stdout / stderr)."""
    e = {**os.environ, **(env or {})}
    e.setdefault("PYTHONIOENCODING", "utf-8")
    return subprocess.run(
        [sys.executable, "-m", "dn.cli", *args],
        cwd=cwd,
        env=e,
        input=input,
        text=True,
        encoding="utf-8",
        capture_output=True,
        timeout=300,
    )


def dn_json(*args: str, **kw: Any) -> tuple[int, dict[str, Any]]:
    p = run_dn(*args, "--json", **kw)
    return p.returncode, json.loads(p.stdout)


# ------------------------------------------------------------------ fake Anthropic client


class FakeMessages:
    def __init__(self, handler: Callable[[dict[str, Any], int], Any]) -> None:
        self.handler = handler
        self.requests: list[dict[str, Any]] = []

    async def create(self, **req: Any) -> Any:
        self.requests.append(req)
        out = self.handler(req, len(self.requests))
        if isinstance(out, BaseException):
            raise out
        tool = req["tools"][0]["name"]
        return SimpleNamespace(
            content=[SimpleNamespace(type="tool_use", name=tool, input=out)],
            usage=SimpleNamespace(
                input_tokens=100, output_tokens=20, cache_read_input_tokens=0, cache_creation_input_tokens=0
            ),
        )


class FakeClient:
    def __init__(self, handler: Callable[[dict[str, Any], int], Any]) -> None:
        self.messages = FakeMessages(handler)

    @property
    def requests(self) -> list[dict[str, Any]]:
        return self.messages.requests


def tool_of(req: dict[str, Any]) -> str:
    return str(req["tools"][0]["name"])


def user_text(req: dict[str, Any]) -> str:
    c = req["messages"][0]["content"]
    if isinstance(c, str):
        return c
    return "\n".join(b.get("text", "") for b in c if isinstance(b, dict))


def _httpx():  # type: ignore[no-untyped-def]
    """anthropic >= 1.0 ships on httpx2; older releases use httpx."""
    try:
        import httpx2

        return httpx2
    except ImportError:
        import httpx

        return httpx


def api_error(status: int) -> Exception:
    import anthropic

    httpx = _httpx()

    resp = httpx.Response(status, request=httpx.Request("POST", "https://api.anthropic.com/v1/messages"))
    if status == 400:
        return anthropic.BadRequestError("bad request", response=resp, body=None)
    if status == 429:
        return anthropic.RateLimitError("rate limited", response=resp, body=None)
    return anthropic.APIStatusError(f"status {status}", response=resp, body=None)


def connection_error() -> Exception:
    import anthropic

    httpx = _httpx()

    return anthropic.APIConnectionError(
        request=httpx.Request("POST", "https://api.anthropic.com/v1/messages")
    )


def make_llm(tmp: Path, client: Any = None, mode: str = "live", **kw: Any):  # type: ignore[no-untyped-def]
    from dn.llm import LLM

    async def no_sleep(_: float) -> None:
        return None

    return LLM(
        model=kw.pop("model", "claude-sonnet-4-6"),
        cache_dir=tmp / "llmcache",
        mode=mode,
        client=client,  # type: ignore[arg-type]
        sleep=kw.pop("sleep", no_sleep),
        **kw,
    )


def label(category: str, confidence: float = 0.9, **kw: Any) -> dict[str, Any]:
    return {
        "category": category,
        "subcategory": kw.get("subcategory"),
        "confidence": confidence,
        "title": kw.get("title", "Title"),
        "date": kw.get("date"),
        "summary": kw.get("summary", "summary"),
        "tags": kw.get("tags", []),
        "has_domain_knowledge": kw.get("has_domain_knowledge", True),
    }


def tree_state(root: Path, exclude: tuple[str, ...] = (".dn", "organized")) -> dict[str, tuple[str, int]]:
    """relative path -> (sha256, mtime_ns) for every file outside dn's own artifacts."""
    import hashlib

    out: dict[str, tuple[str, int]] = {}
    for p in sorted(root.rglob("*")):
        rel = p.relative_to(root).as_posix()
        if not p.is_file() or rel.split("/", 1)[0] in exclude:
            continue
        out[rel] = (hashlib.sha256(p.read_bytes()).hexdigest(), p.stat().st_mtime_ns)
    return out


def batch_sections(req: dict[str, Any]) -> list[tuple[str, str]]:
    """(file_id, section text) pairs of a submit_classify_batch request."""
    import re as _re

    text = user_text(req)
    parts = _re.split(r"^=== file_id: (\S+) ===$", text, flags=_re.M)
    return [(parts[i], parts[i + 1]) for i in range(1, len(parts) - 1, 2)]


def batch_aware(single: Callable[[dict[str, Any], int], Any]) -> Callable[[dict[str, Any], int], Any]:
    """Answer submit_classify_batch by asking ``single`` once per file section."""

    def handler(req: dict[str, Any], n: int) -> Any:
        if tool_of(req) != "submit_classify_batch":
            return single(req, n)
        labels = []
        for fid, section in batch_sections(req):
            item_schema = req["tools"][0]["input_schema"]["properties"]["labels"]["items"]
            fake = {
                **req,
                "tools": [{**req["tools"][0], "name": "submit_classify", "input_schema": item_schema}],
                "messages": [{"role": "user", "content": section}],
            }
            out = single(fake, n)
            if isinstance(out, BaseException):
                return out
            labels.append({"file_id": fid, **out})
        return {"labels": labels}

    return handler


def smart_handler(overrides: dict[str, Any] | None = None) -> Callable[[dict[str, Any], int], Any]:
    """Valid output for every dn tool; ``overrides[tool]`` may be a value or ``fn(req, n)``."""
    overrides = overrides or {}

    def handler(req: dict[str, Any], n: int) -> Any:
        tool = tool_of(req)
        if tool in overrides:
            v = overrides[tool]
            return v(req, n) if callable(v) else v
        text = user_text(req)
        if tool == "submit_classify":
            enum = req["tools"][0]["input_schema"]["properties"]["category"]["enum"]
            return label(enum[0], 0.9, title="Doc", summary="A document", tags=["t"])
        if tool == "submit_distill":
            return {
                "terms": [
                    {"term": "API Gateway", "definition": "Routes requests", "aliases": [], "locator": "L1"}
                ],
                "entities": [
                    {"name": "API Gateway", "type": "system", "description": "gateway", "locator": "L1"}
                ],
                "facts": [
                    {
                        "statement": "The rate limit is 100 rps.",
                        "subject": "rate limit",
                        "predicate": "is",
                        "object": "100 rps",
                        "confidence": 0.9,
                        "locator": "L2",
                    }
                ],
                "relations": [],
                "questions": [],
            }
        if tool == "submit_normalize":
            import re as _re

            pairs = [json.loads(ln) for ln in text.splitlines() if ln.startswith("{")]
            return {
                "pairs": [
                    {
                        "a": p["a"],
                        "b": p["b"],
                        "same": p["a"].casefold() == p["b"].casefold(),
                        "canonical": p["a"],
                    }
                    for p in pairs
                ]
            }
        if tool == "submit_topics":
            return {"topics": []}
        if tool == "submit_topic_doc":
            import re as _re

            ids = _re.findall(r"^(F-\d+):", text, _re.M)
            return {"markdown": "## Body\n\nText." + (f" [src: {ids[0]}]" if ids else "")}
        if tool in ("submit_overview", "submit_index"):
            return {"markdown": "## Summary\n\nOverview text."}
        if tool == "submit_vision":
            return {"transcript": "text", "description": "image"}
        if tool == "submit_propose_taxonomy":
            return {
                "categories": [
                    {"slug": f"c{i}", "name": f"C{i}", "description": "d", "examples": []} for i in range(5)
                ]
            }
        raise AssertionError(f"unexpected tool {tool}")

    return handler if "submit_classify_batch" in overrides else batch_aware(handler)


def make_pdf(text: str) -> bytes:
    """A one-page text PDF (used where an AC names a .pdf file)."""
    import pymupdf

    doc = pymupdf.open()
    page = doc.new_page()
    page.insert_textbox(
        pymupdf.Rect(50, 50, 550, 800), text + " " + "filler text for the page. " * 4, fontsize=11
    )
    data: bytes = doc.tobytes()
    doc.close()
    return data
